<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Square.Cli</RootNamespace>
    <AssemblyName>square</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Square.Domain\Square.Domain.csproj" />
    <ProjectReference Include="..\Square.Contracts\Square.Contracts.csproj" />
    <ProjectReference Include="..\Square.Application\Square.Application.csproj" />
  </ItemGroup>
</Project>
