<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Square.Desktop</RootNamespace>
    <AssemblyName>square-ui</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Square.Contracts\Square.Contracts.csproj" />
  </ItemGroup>
</Project>
