<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Square.Adapters.CommandCode</RootNamespace>
    <AssemblyName>Square.Adapters.CommandCode</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Square.Domain\Square.Domain.csproj" />
    <ProjectReference Include="..\Square.Contracts\Square.Contracts.csproj" />
    <ProjectReference Include="..\Square.Adapters.Abstractions\Square.Adapters.Abstractions.csproj" />
  </ItemGroup>
</Project>
