<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Persistence_Tests</RootNamespace>
    <AssemblyName>Persistence.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <SquareTestCategory>Deterministic</SquareTestCategory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Square.Persistence.Sqlite\Square.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\Square.TestKit\Square.TestKit.csproj" />
  </ItemGroup>
</Project>
