<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Contract_Tests</RootNamespace>
    <AssemblyName>Contract.Tests</AssemblyName>
    <IsTestProject>true</IsTestProject>
    <SquareTestCategory>Deterministic</SquareTestCategory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Square.Domain\Square.Domain.csproj" />
    <ProjectReference Include="..\..\src\Square.Contracts\Square.Contracts.csproj" />
    <ProjectReference Include="..\Square.TestKit\Square.TestKit.csproj" />
  </ItemGroup>
</Project>
