<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Square.Application</RootNamespace>
    <AssemblyName>Square.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Square.Domain\Square.Domain.csproj" />
    <ProjectReference Include="..\Square.Contracts\Square.Contracts.csproj" />
  </ItemGroup>
</Project>
